from collections import namedtuple

first_confidence_survey = ['date', 'identifier', 'gender', 'gender_other', 'gpa', 'major', 'graduating_year',
                           'confidence_prepared',
                           'confidence_ability', 'confidence_general_classes', 'confidence_major',
                           'confidence_get_degree', 'confidence_percentile']

first_confident_person = namedtuple('Confident_person', first_confidence_survey)

middle_confidence_survey = ['date', 'identifier', 'confidence_general_classes', 'confidence_major_classes',
                            'confidence_excel_graduate', 'confidence_get_degree', 'confidence_percentile']

middle_confidence_person = namedtuple('middle_confident_person', middle_confidence_survey)
#
# last_confidence_survey = ['date', 'identifier', 'confidence_general_classes', 'confidence_major_classes', 'confidence_excel_graduate',
#                           'confidence_get_degree', 'confidence_career', 'confidence_percentile', '1_grade', '1_class',
#                           '2_grade', '2_class', '3_grade', '3_class', '4_grade', '4_class']

# last_confidence_person = namedtuple('last_confidence_person', last_confidence_survey)

ques_ans = {'duration_seconds': 'int', 'Location_Latitude': 'double', 'LocationLongitude': 'double',
            'consent_current': 'string', 'consent_future': 'string', 'email': 'string', 'gender': 'string',
            'gender_other': 'race', 'race': 'int', 'age': 'string', 'university_program': 'double',
            'university_major': 'string', 'university_minor': 'string', 'university_courses_fall': 'courses',
            'university_graduation_year': 'string', 'university_gpa': 'string', 'university_gpa_TEXT': 'double',
            'received_internship_offer': 'yes_no', 'extracurriculars': 'extracurriculars',
            'major_pros': 'encouragement',
            'major_pros_TEXT': 'string', 'major_cons': 'barriers', 'major_cons_TEXT': 'string',
            'confidence_graduate_gpa': 'agreement', 'confidence_prepared_courses': 'agreement',
            'confidence_percentile': 'double', 'participation_questions_comfortable_NONCS': 'comfort',
            'participation_absent_frequency': 'frequency_absent',
            'participation_questions_ask_frequency': 'frequency_class_typo',
            'participation_questions_comfortable': 'comfort',
            'participation_not_questions_frequency': 'frequency_class', 'participation_absent_why': 'miss_class',
            'participation_MORE_comfortable': 'increase_comfort', 'participation_LESS_comfortable': 'decrease_comfort',
            'participation_not_reasons': 'participate_decrease',
            'participation_questions_ask_ignored': 'frequency_class_typo',
            'participation_group_project_role': 'responsibilities', 'professors_ask_advice': 'frequency_typo',
            'professors_encouraged_you': 'professor_encouragement', 'participation_TA_session': 'frequency_TA_typo',
            'participation_TA_ask_questions': 'frequency_typo', 'participation_talk_peers': 'frequency',
            'courses_professors_engaging': 'agreement', 'professors_represent_diversity': 'agreement',
            'role_models_same_gender': 'agreement', 'participation_peers_help_you': 'frequency_typo',
            'participation_peers_you_serve': 'frequency_typo', 'participation_clubs': 'meetings_clubs',
            'participation_friends_CS_students': 'percentage', 'friends_CS_students_want_more': 'agreement',
            'scholarship': 'scholarships', 'extracurricular_plans_before_graduation': 'involvement',
            'frequency_balance_career_parenthood': 'frequency', 'professors_declare_parent': 'frequency_typo',
            'professors_declare_full_time': 'frequency_typo', 'department_sexist_you': 'certainty',
            'department_sexist_others': 'certainty', 'department_success_because_gender': 'certainty',
            'department_appearance': 'frequency_typo', 'department_appearance_comments': 'appearance_comments',
            'complaints_how': 'certainty', 'complaints_concequences': 'certainty',
            'complaints_concequences_fear': 'certainty', 'peer_mistreated_react': 'sexism_response',
            'people_surprise_major': 'agreement', 'people_sexist_jokes_gender': 'frequency_typo',
            'highest_standard': 'student_groups_standards', 'peer_sexism_ignoring_suggestion': 'frequency_typo',
            'friends_other_gender': 'agreement', 'intelligence_fixed': 'agreement',
            'intelligence_malleable': 'agreement',
            'failure_lazy': 'agreement', 'failure_environment': 'agreement', 'failure_ability': 'agreement',
            'describe_positive_experience': 'string', 'describe_negative_experience': 'string',
            'suggestion_improve_institution': 'string'}

short_to_long = {'duration_seconds': 'How long between opening and submitting survey?', 'Location_Latitude': 'latitude',
                 'LocationLongitude': 'longitude',
                 'consent_current': 'Please read the entire text above before selecting an answer below.',
                 'consent_future': 'Are you willing to participate more in this study of students at BYU? - Selected Choice',
                 'email': 'Are you willing to participate more in this study of students at BYU? - Yes - please enter your email address here - Text',
                 'gender': 'What gender do you identify with? - Selected Choice',
                 'gender_other': 'What gender do you identify with? - Other - Text',
                 'race': 'What is your race/ethnicity (select all that apply)?', 'age': 'How old are you?',
                 'university_program': 'What degree are you currently pursuing?',
                 'university_major': 'What is your intended major?',
                 'university_minor': 'What is your minor/secondary major?',
                 'university_courses_fall': 'What CS courses will you enroll in during the fall semester of 2018? (select all that apply)',
                 'university_graduation_year': 'When do you anticipate graduating?',
                 'university_gpa': 'What is your current GPA at this university? - Selected Choice',
                 'university_gpa_TEXT': 'What is your current GPA at this university? - My current overall GPA is: - Text',
                 'received_internship_offer': 'Have you ever been offered a CS-related internship?',
                 'extracurriculars': 'What extracurriculars have you pursued in high school or college? (select all that apply)',
                 'major_pros': 'What factors influenced your decision to pick your major? (select all that apply) - Selected Choice',
                 'major_pros_TEXT': 'What factors influenced your decision to pick your major? (select all that apply) - Specific BYU courses or labs (list courses here please) - Text',
                 'major_cons': 'What do you perceive as being a barrier to your completion of this major and your career in this field? (select all that apply) - Selected Choice',
                 'major_cons_TEXT': 'What do you perceive as being a barrier to your completion of this major and your career in this field? (select all that apply) - Specific BYU courses or labs (list courses here please) - Text',
                 'confidence_graduate_gpa': 'How much do you agree with the following statement: I am confident in my ability to graduate with a 3.0 or higher major GPA (your major GPA does not include AP/IB credits or general education/GE classes).',
                 'confidence_prepared_courses': 'How much do you agree with the following statement: I am prepared for my CS course(s) next semester.',
                 'confidence_percentile': 'With respect to your peers in your major, what percentile would you rank yourself at? Please enter a number between 0 and 100.',
                 'participation_questions_comfortable_NONCS': 'How comfortable are you asking questions in your non-CS courses?',
                 'participation_absent_frequency': 'How often are you absent from your CS class(es)?',
                 'participation_questions_ask_frequency': 'On average how often do you ask questions in CS courses?',
                 'participation_questions_comfortable': 'How comfortable are you asking questions in your CS courses?',
                 'participation_not_questions_frequency': 'Aside from asking questions how often do you participate (answer questions/talk in discussions/etc) in CS courses?',
                 'participation_absent_why': 'When you miss a CS class what is most often the reason why? (only select one)',
                 'participation_MORE_comfortable': 'What helps you feel MORE COMFORTABLE asking questions in your CS course(s)? (select all that apply)',
                 'participation_LESS_comfortable': 'When do you feel LESS COMFORTABLE asking questions in your CS course(s)? (select all that apply)',
                 'participation_not_reasons': 'Why do you not participate (aside from asking questions: answering questions/participating in discussions/etc) more in your CS course(s)?',
                 'participation_questions_ask_ignored': 'How often do you raise your hand in a CS class but never get called on?',
                 'participation_group_project_role': 'In group projects for CS courses which tasks do you typically take responsibility for? (select all that apply)',
                 'professors_ask_advice': 'How often do you discuss your academic performance or career plans with a professor or faculty member? (during office hours or in other one-on-one situations)',
                 'professors_encouraged_you': 'Has as a CS professor ever invited you  personally to consider any of the following? (select all that apply)',
                 'participation_TA_session': 'How often do you go to TA-led help sessions for CS courses?',
                 'participation_TA_ask_questions': 'How often to you visit the CS TAs to ask questions?',
                 'participation_talk_peers': 'How often do you talk with other students (not TAs) while in the CS TA cubicals or CS labs?',
                 'courses_professors_engaging': 'How strongly do you agree with the statement: CS professors and CS courses are engaging.',
                 'professors_represent_diversity': 'How strongly do you agree with the statement: I feel that the CS professors adequately represent the diverse backgrounds/views/demographics/perspectives of students in CS courses.',
                 'role_models_same_gender': 'Do you feel like you have role models of the same gender as you who do CS?',
                 'participation_peers_help_you': 'How often have you asked another student (not a TA for the course) to help you understand CS course material?',
                 'participation_peers_you_serve': 'How often have you mentored any students in the CS major or CS courses this semester? (assisted them with labs/homework/or given internship/job or graduate school advice)',
                 'participation_clubs': 'Do you attend meetings/events for any of the following? (select all that apply)',
                 'participation_friends_CS_students': 'What percentage of your friends are taking classes in the CS department?',
                 'friends_CS_students_want_more': 'How much do you agree with the following statement: I want to make more friends in the CS major.',
                 'scholarship': 'Have you been the recipient of an academic scholarship? (select all that apply)',
                 'extracurricular_plans_before_graduation': 'Which of the following have you done or do you plan to do before you graduate? (select all that apply)',
                 'frequency_balance_career_parenthood': 'How often do members of the CS department (students/TAs/professors/etc) ask you about your plans to balance a career and parenthood?',
                 'professors_declare_parent': 'How often do members of the CS department (students/TAs/professors/etc) tell you that you should be a stay-at-home parent?',
                 'professors_declare_full_time': 'How often do members of the CS department (students/TAs/professors/etc) tell you that you should pursue a full-time career?',
                 'department_sexist_you': 'Do you feel like a member of the CS department (students/TAs/professors/etc) has treated you differently than your peers of the opposite gender?',
                 'department_sexist_others': 'Are you aware of CS classmates who believe they have been treated differently by members of the CS department (students/TAs/professors/etc) because of their gender?',
                 'department_success_because_gender': 'Has a member of the CS department (students/TAs/professors/etc)you ever been told that you earned a good grade/got a job/internship/or scholarship offer because of your gender?',
                 'department_appearance': 'How often do you get negative comments about your appearance or attire from members of the CS department (students/TAs/professors/etc)?',
                 'department_appearance_comments': 'If members of the CS department (students/TAs/professors/etc) make negative comments about your appearance what do they comment about? (select all that apply)',
                 'complaints_how': 'Do you know how to file complaints for being treated differently because of your gender in the CS department?',
                 'complaints_concequences': 'Do you know what happens if a complaint is filed against a member of the CS department who is accused of being sexist?',
                 'complaints_concequences_fear': 'Would you personally be worried about retribution if you filed a complaint about someone treating you or a peer differently because of your/their gender?',
                 'peer_mistreated_react': 'If you saw a peer treat someone differently because of their gender (through words/actions/etc) would you say or do something? (select all that apply)',
                 'people_surprise_major': 'When you tell people what your major is how often do they express surprise (You dont look/act like a ____ major/Why are you majoring in ____?)?',
                 'people_sexist_jokes_gender': 'How often do you hear people in the CS department make sexist remarks or jokes about your gender?',
                 'highest_standard': 'Do you feel that some students are held to a higher standard than other students in the CS department? If so please select all groups that apply.',
                 'peer_sexism_ignoring_suggestion': 'How often within the CS department do you make a suggestion that was not considered until another person makes the same suggestion?',
                 'friends_other_gender': 'Do you feel like you can have non-romantic friends of the opposite gender?',
                 'intelligence_fixed': 'How strongly do you agree with the statement: Intelligence is a fixed trait; you are born with the talents that you have and nothing you do can change them.',
                 'intelligence_malleable': 'How strongly do you agree with the statement: Intelligence is a malleable quality if you work hard and practice you will improve.',
                 'failure_lazy': 'How strongly do you agree with the statement: Failure or a lack of achievement is due to insufficient effort.',
                 'failure_environment': 'How strongly do you agree with the statement: Failure or a lack of achievement is due to personal or environmental obstacles.',
                 'failure_ability': 'How strongly do you agree with the statement: Failure or a lack of achievement is due to a lack of ability.',
                 'describe_positive_experience': 'Are there any positive experiences or interactions that you had with members of the CS department that you would like to share?',
                 'describe_negative_experience': 'Are there any negative experiences or interactions that you had with members of the CS department that you would like to share?',
                 'suggestion_improve_institution': "What one change would you most like to see implemented to improve students' experiences at this institution?"}
