from data_structures import *

AGE = 'Q80'
RACE = 'Q81'
GENDER = 'Q3'
PROGRAM = 'Q4'
MAJOR = 'Q5'
MINOR = 'Q6'
FALL_COURSES = 'Q7'
GRAD_YEAR = 'Q73'
GPA = 'Q74_2_TEXT'
INTERNSHIP_OFFER = 'Q50'
EXTRACURRICULARS = 'Q8'
MAJOR_PROS = 'Q10'
MAJOR_PROS_CLASS = 'Q10_21_TEXT	'
MAJOR_CONS = 'Q11'
MAJOR_CONS_CLASS = 'Q11_14_TEXT'
CONFIDENCE_GRAD_GPA = 'Q68'
CONFIDENCE_PREPARED_COURSES = 'Q88'
CONFIDENCE_PERCENTILE_PEERS = 'Q93'
COURSES_QUESTION_COMFORT = 'Q86'
COURSES_ABSENT_FREQUENCY = 'Q84'
PARTICIPATION_QUESTIONS_ASK_FREQUENCY = 'Q16'
COURSES_ASKING_QUESTIONS_COMFORT = 'Q15'
PARTICIPATION_NOT_QUESTIONS_FREQUENCY = 'Q90'
PARTICIPATION_ABSENT_WHY = 'Q83'
PARTICIPATION_MORE_COMFORTABLE = 'Q91'
PARTICIPATION_LESS_COMFORTABLE = 'Q85'
PARTICIPATION_NOT_REASONS = 'Q92'
PARTICIPATION_QUESTIONS_ASK_IGNORED = 'Q57'
PARTICIPATION_GROUP_PROJECT_ROLE = 'Q46'
PROFESSORS_ASK_ADVICE = 'Q18'
PROFESSORS_ENCOURAGED_YOU = 'Q19'
PARTICIPATION_TA_SESSION = 'Q21'
PARTICIPATION_TA_ASK_QUESTIONS = 'Q22'
PARTICIPATION_TALK_PEERS = 'Q52'
COURSES_PROFESSORS_ENGAGING = 'Q20'
PROFESSORS_REPRESENT_DIVERSITY = 'Q59'
ROLE_MODELS_SAME_GENDER = 'Q63'
PARTICIPATION_PEERS_HELP_YOU = 'Q26'
PARTICIPATION_PEERS_YOU_SERVE = 'Q25'
PARTICIPATION_CLUBS = 'Q27'
PARTICIPATION_FRIENDS_CS_STUDENTS = 'Q28'
FRIENDS_CS_STUDENTS_WANT_MORE = 'Q82'
SCHOLARSHIP = 'Q48'
EXTRACURRICULAR_PLANS_BEFORE_GRADUATION = 'Q9'
FREQUENCY_BALANCE_CAREER_PARENTHOOD = 'Q32'
PROFESSORS_DECLARE_PARENT = 'Q31'
PROFESSORS_DECLARE_FULL_TIME = 'Q30'
DEPARTMENT_SEXIST_YOU = 'Q41'
DEPARTMENT_SEXIST_OTHERS = 'Q42'
# Q35
DEPARTMENT_APPEARANCE = 'Q62'
DEPARTMENT_APPEARANCE_COMMENTS = 'Q61'
COMPLAINTS_HOW = 'Q38'
COMPLAINTS_CONCEQUENCES = 'Q39'
COMPLAINTS_CONCEQUENCES_FEAR = 'Q40'
PEER_MISTREATED_REACT = 'Q51'
PEOPLE_SURPRISE_MAJOR = 'Q60'
PEOPLE_SEXIST_JOKES_GENDER = 'Q58'
HIGHEST_STANDARD = 'Q60'
PEER_SEXISM_IGNORING_SUGGESTION = 'Q61'
FRIENDS_OTHER_GENDER = 'Q56'
INTELLIGENCE_FIXED = 'Q75'
INTELLIGENCE_MALLEABLE = 'Q76'
FAILURE_LAZY = 'Q77'
FAILURE_ENVIRONMENT = 'Q78'
FAILURE_ABILITY = 'Q79'
DESCRIBE_NEGATIVE_EXPERIENCE = 'Q68'
DESCRIBE_POSITIVE_EXPERIENCE = 'Q67'
SUGGESTION_IMPROVE_INSTITUTION = 'Q54'


FOCUS_VARS = [MAJOR, PROGRAM, GRAD_YEAR]
# GENDER IS NOT INCLUDED BECAUSE WE USE GENDER FOR EVERYTHING
# [AGE, RACE, GENDER, PROGRAM, MAJOR, MINOR, GRAD_YEAR, GPA]
ONE_CHOICE_QUESTIONS = [INTERNSHIP_OFFER, CONFIDENCE_GRAD_GPA, CONFIDENCE_PREPARED_COURSES, CONFIDENCE_PREPARED_COURSES,
                        FALL_COURSES, EXTRACURRICULARS, PARTICIPATION_QUESTIONS_ASK_FREQUENCY,
                        COURSES_ASKING_QUESTIONS_COMFORT, PARTICIPATION_NOT_QUESTIONS_FREQUENCY,
                        PARTICIPATION_ABSENT_WHY, PARTICIPATION_NOT_REASONS, PARTICIPATION_QUESTIONS_ASK_IGNORED,
                        PROFESSORS_ASK_ADVICE, PARTICIPATION_TA_ASK_QUESTIONS, PARTICIPATION_TALK_PEERS,
                        COURSES_PROFESSORS_ENGAGING, PROFESSORS_REPRESENT_DIVERSITY, ROLE_MODELS_SAME_GENDER,
                        PARTICIPATION_PEERS_HELP_YOU, PARTICIPATION_PEERS_YOU_SERVE, PARTICIPATION_FRIENDS_CS_STUDENTS,
                        FRIENDS_CS_STUDENTS_WANT_MORE, FREQUENCY_BALANCE_CAREER_PARENTHOOD, PROFESSORS_DECLARE_PARENT,
                        PROFESSORS_DECLARE_FULL_TIME, DEPARTMENT_SEXIST_YOU, DEPARTMENT_SEXIST_OTHERS,
                        DEPARTMENT_APPEARANCE, COMPLAINTS_HOW, COMPLAINTS_CONCEQUENCES, COMPLAINTS_CONCEQUENCES_FEAR,
                        PEOPLE_SURPRISE_MAJOR, PEOPLE_SEXIST_JOKES_GENDER, PEER_SEXISM_IGNORING_SUGGESTION,
                        INTELLIGENCE_FIXED]

TEXT_ANSWERS = [MAJOR_CONS_CLASS, MAJOR_CONS_CLASS]

NUMBER_ANSWERS = [GPA, CONFIDENCE_PERCENTILE_PEERS, AGE]

MANY_CHOICES_QUESTIONS = [MAJOR_PROS, MAJOR_CONS, EXTRACURRICULARS, PARTICIPATION_MORE_COMFORTABLE,
                          PARTICIPATION_LESS_COMFORTABLE, PARTICIPATION_GROUP_PROJECT_ROLE, PROFESSORS_ENCOURAGED_YOU,
                          PARTICIPATION_CLUBS, PARTICIPATION_ABSENT_WHY, EXTRACURRICULAR_PLANS_BEFORE_GRADUATION,
                          DEPARTMENT_APPEARANCE_COMMENTS, PARTICIPATION_FRIENDS_CS_STUDENTS, PARTICIPATION_NOT_REASONS,
                          PEER_MISTREATED_REACT, HIGHEST_STANDARD, SCHOLARSHIP]

question_number_to_expected_answer = {
    'Q8': extracurriculars,
    'Q10': encouragement,  # MAJOR_PROS
    'Q11': barriers,  # MAJOR_CONS
    'Q68': agreement,  # CONFIDENCE_PREPARED_COURSES
    'Q88': agreement,  # CONFIDENCE_PERCENTILE_PEERS
    'Q84': frequency_absent,  # COURSES_ABSENT_FREQUENCY
    'Q16': frequency_class,  # PARTICIPATION_QUESTIONS_ASK_FREQUENCY
    'Q15': comfort,  # COURSES_ASKING_QUESTIONS_COMFORT
    'Q90': frequency_class,  # PARTICIPATION_NOT_QUESTIONS_FREQUENCY
    'Q83': miss_class,  # PARTICIPATION_ABSENT_WHY
    'Q91': increase_comfort,  # PARTICIPATION_MORE_COMFORTABLE
    'Q85': decrease_comfort,  # PARTICIPATION_LESS_COMFORTABLE
    'Q92': not_participate_reasons,  # PARTICIPATION_NOT_REASONS
    'Q57': frequency_class,  # PARTICIPATION_QUESTIONS_ASK_IGNORED
    'Q46': responsibilities,  # PARTICIPATION_GROUP_PROJECT_ROLE
    'Q18': frequency,  # PROFESSORS_ASK_ADVICE
    'Q19': professor_encouragement,  # PROFESSORS_ENCOURAGED_YOU
    'Q21': frequency_TA,  # PARTICIPATION_TA_SESSION
    'Q22': frequency,  # PARTICIPATION_TA_ASK_QUESTIONS
    'Q52': frequency,  # PARTICIPATION_TALK_PEERS
    'Q20': agreement,  # COURSES_PROFESSORS_ENGAGING
    'Q59': agreement,  # PROFESSORS_REPRESENT_DIVERSITY
    'Q63': agreement,  # ROLE_MODELS_SAME_GENDER
    'Q26': frequency,  # PARTICIPATION_PEERS_HELP_YOU
    'Q25': frequency,  # PARTICIPATION_PEERS_YOU_SERVE
    'Q27': meetings_clubs,  # PARTICIPATION_CLUBS
    'Q28': percentage,  # PARTICIPATION_FRIENDS_CS_STUDENTS
    'Q82': agreement,  # FRIENDS_CS_STUDENTS_WANT_MORE
    'Q48': scholarships,  # SCHOLARSHIP
    'Q9': involvement,  # EXTRACURRICULAR_PLANS_BEFORE_GRADUATION
    'Q32': frequency,  # FREQUENCY_BALANCE_CAREER_PARENTHOOD
    'Q31': frequency,  # PROFESSORS_DECLARE_PARENT
    'Q30': frequency,  # PROFESSORS_DECLARE_FULL_TIME
    'Q41': certainty,  # DEPARTMENT_SEXIST_YOU
    'Q42': certainty,  # DEPARTMENT_SEXIST_OTHERS
    # Q35 # Has a member of the CS department (students, TAs, professors, etc) ever told you that you earned a good grade, got a job, internship, or scholarship offer because of your gender?
    'Q62': frequency,  # DEPARTMENT_APPEARANCE
    'Q61': appearance_comments,  # DEPARTMENT_APPEARANCE_COMMENTS # TODO
    'Q38': certainty,  # COMPLAINTS_HOW
    'Q39': certainty,  # COMPLAINTS_CONCEQUENCES
    'Q40': certainty,  # COMPLAINTS_CONCEQUENCES_FEAR
    'Q51': sexism_response,  # PEER_MISTREATED_REACT
    'Q60': agreement,  # PEOPLE_SURPRISE_MAJOR # TODO
    'Q58': frequency,  # PEOPLE_SEXIST_JOKES_GENDER
    'Q60': student_groups_standards,  # HIGHEST_STANDARD # TODO
    'Q61': frequency,  # PEER_SEXISM_IGNORING_SUGGESTION
    'Q56': agreement,  # FRIENDS_OTHER_GENDER
    'Q75': agreement,  # INTELLIGENCE_FIXED
    'Q76': agreement,  # INTELLIGENCE_MALLEABLE
    'Q77': agreement,  # FAILURE_LAZY
    'Q78': agreement,  # FAILURE_ENVIRONMENT
    'Q79': agreement,  # FAILURE_ABILITY
}
